In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('tabular_data/listing.csv')
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [ ]:
df_copy=df.copy()
df_copy

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
4,8b2d0f78-16d8-4559-8692-62ebce2a1302,Treehouses,Hanging cabin,"['About this space', 'Feel refreshed at this u...","['What this place offers', 'Heating and coolin...",Wargnies-le-Petit Hauts-de-France France,2,1.0,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,5.0,https://www.airbnb.co.uk/rooms/50166553?adults...,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
986,de8a45c7-0a1e-48ed-916d-6d1ad8d9f771,Beachfront,Unspoilt Sea View Family Beach House,"['About this space', 'Sleeps 10. A large Beach...","['What this place offers', 'Scenic views', 'Be...",Pevensey Bay England United Kingdom,10,7.0,5.0,426,NaN,NaN,NaN,NaN,NaN,NaN,41.0,https://www.airbnb.co.uk/rooms/46632639?adults...,5,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
 19  Unnamed: 19           1 non-null      float64
dtypes: float64(10), int64(1), object(9)
memory usage: 154.5+ KB

In [ ]:
df.describe()

,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,Unnamed: 19
count,945.000000,888.000000,988.000000,890.000000,890.000000,890.000000,890.000000,890.000000,890.000000,988.000000,1.0
mean,2.529101,1.443694,161.115385,5.071573,4.903146,4.932022,4.903596,4.943146,4.764157,33.765891,3.0
std,1.910456,0.913499,212.175681,6.543922,0.135121,0.122210,0.121337,0.103609,0.181936,14.721196,NaN
min,1.000000,0.000000,3.000000,3.800000,4.000000,3.900000,4.000000,3.900000,3.300000,2.000000,3.0
25%,1.000000,1.000000,84.000000,4.800000,4.900000,4.900000,4.900000,4.900000,4.700000,23.000000,3.0
50%,2.000000,1.000000,120.000000,4.900000,4.900000,5.000000,4.900000,5.000000,4.800000,33.000000,3.0
75%,3.000000,1.500000,181.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.900000,43.000000,3.0
max,17.000000,10.000000,5427.000000,200.000000,5.000000,5.000000,5.000000,5.000000,5.000000,84.000000,3.0

In [ ]:
df['Category'].value_counts()

Category
Treehouses       243
Offbeat          204
Amazing pools    197
Chalets          196
Beachfront       148
Name: count, dtype: int64

In [ ]:
df.isnull()

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
984,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
985,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
986,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,False,False,False,True
987,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
df.isnull().sum()

ID                        0
Category                  0
Title                     0
Description              88
Amenities                 0
Location                  0
guests                   19
beds                     43
bathrooms               100
Price_Night               0
Cleanliness_rating       98
Accuracy_rating          98
Communication_rating     98
Location_rating          98
Check-in_rating          98
Value_rating             98
amenities_count           0
url                       0
bedrooms                 82
Unnamed: 19             987
dtype: int64

In [ ]:
df.dtypes

ID                       object
Category                 object
Title                    object
Description              object
Amenities                object
Location                 object
guests                   object
beds                    float64
bathrooms               float64
Price_Night               int64
Cleanliness_rating      float64
Accuracy_rating         float64
Communication_rating    float64
Location_rating         float64
Check-in_rating         float64
Value_rating            float64
amenities_count         float64
url                      object
bedrooms                 object
Unnamed: 19             float64
dtype: object

In [ ]:
def remove_rows_with_missing_ratings(df):
    df.dropna(subset=['Cleanliness_rating','Accuracy_rating','Communication_rating','Location_rating','Check-in_rating','Value_rating'])
    return df

In [ ]:
remove_rows_with_missing_ratings(df)

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
5,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"['About this space', 'Charming cabin nestled i...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,cfbc88da-e88c-415a-b397-108d0948c4ba,Beachfront,Lancing Beach Apartment,"['About this space', 'An apartment directly on...","['What this place offers', 'Bathroom', 'Hair d...",Lancing United Kingdom,4,2.0,1.5,240,4.9,5.0,5.0,5.0,4.9,4.8,33.0,https://www.airbnb.co.uk/rooms/12680472?adults...,2,NaN
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [ ]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
5,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"['About this space', 'Charming cabin nestled i...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,cfbc88da-e88c-415a-b397-108d0948c4ba,Beachfront,Lancing Beach Apartment,"['About this space', 'An apartment directly on...","['What this place offers', 'Bathroom', 'Hair d...",Lancing United Kingdom,4,2.0,1.5,240,4.9,5.0,5.0,5.0,4.9,4.8,33.0,https://www.airbnb.co.uk/rooms/12680472?adults...,2,NaN
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [ ]:
df.isnull().sum()

ID                        0
Category                  0
Title                     0
Description              60
Amenities                 0
Location                  0
guests                   18
beds                     34
bathrooms                79
Price_Night               0
Cleanliness_rating        0
Accuracy_rating           0
Communication_rating      0
Location_rating           0
Check-in_rating           0
Value_rating              0
amenities_count           0
url                       0
bedrooms                 76
Unnamed: 19             889
dtype: int64

In [ ]:
df['Description'][1]

'[\'About this space\', "Come and spend a romantic stay with a couple or family, on the Domaine de l \'Arbre in Cabane\\n\\nA very pretty forest of 5 hectares shelters 8 beautiful huts they all have the dream names, unique and unprecedented.\\n\\nThey are housed in centuries-old trees out of sight, in osmosis with nature.\\n\\nThe site is preserved, your peace is assured. Nature is everywhere\\n\\nA treehouse to indulge, relax and go where no one will be looking for you!", \'The space\', \'The space\\nCabin perched in trees 8 meters high.\\nThis cabin is beautiful. Its access via a board walkway and its platform adjoining 3 individual beds seduce them to the highest degree. It has a capacity of 3 people.\', \'Guest access\', \'Guest access\\nYou will have access to the entire cabin, forest and park.\\nSanitary facilities (showers and toilets) are at the reception, a 3-minute walk.\', \'Other things to note\', \'Other things to note\\nAre you ready for an unusual stay?\']'

In [ ]:
df['Description'][2]

'[\'About this space\', \'Rustic cabin between the pines, 3 meters high and 28 square meters on the banks of the Austreberth River üå≤üèïÔ∏èüå≤\', \'The space\', "The space\\nOur cabin between the pines is a great alternative for those looking for contact with nature and want to rest, enjoy together or have fun with family or friends. With 3 meters high and 28 square meters, it accommodates 4 people. Located on a 1.2 hectare property by the river Austreberthe, our rustic treehouse shares the space with our garden rabbits and dumplings, as well as wild dumplings and our beloved khenty mare, who loves apples and carrots. A tranquil retreat, with efficient thermal insulation and heaters for the colder days. Equipped with a double bed, sofa bed, kitchen , duvet and toilet.\\n\\n\\nWe provide:\\nTowels\\nBed linens and pillows\\nKitchen detergent and bathroom soap\\nPaper towels & toilet paper\\nCooking utensils\\nCoffee, tea, salt and pepper, herbs of provence\\nWhat to do in the area\'s guide\\n\\nI\'ll follow us on Instagram @entreespins", \'Guest access\', \'Guest access\\nGuests can use the space around the cabin.\', \'Other things to note\', "Other things to note\\n*When it\'s windy, the cabin squeaks, but there\'s nothing to worry about.\\n\\n*Do not use candles or objects containing a fire inside and outside the cabin as the polyester is flammable.\\n\\n*Smoking outside only please.\\n\\n*Our dear pets are allowed but with the commitment of their guardian not to leave them on the bed and furnishing fabrics, as well as being responsible for their waste.\\n\\n*Pine needles often fall on the balcony, which doesn\'t mean the space hasn\'t been cleaned.\\n\\n*As this is literally a house between the trees, it is common that there are insects and cobwebs outside but with the door closed it will prevent them from entering the cabin.\\n\\n*With the arrival of the cold season, we see that the internal temperature is between 15 and 18 degrees.\\n\\n*Check-out time must be respected so as not to change the arrival time of the next guest."]'

In [ ]:
df['Description'][0]

'[\'About this space\', "Escape to one of these two fabulous Tree Tents. Suspended high above the canopy, it‚Äôs time to appreciate life from a new perspective. Featured on George Clarke‚Äôs Amazing Spaces, these Tree Tents are a feat of aviation technology. Tree Tent comes complete with fire pit, outdoor kitchen and shower with hot water. You‚Äôll discover a comfortable bed and cosy wood burning stove. Part of the Red Kite Estate, along with our barn and its sister tree tent, the first ever built in the UK, Dragon\'s Egg.", \'The space\', \'The space\\nThe true joy of this place is how wonderfully simple it is (aviation technology aside). Days are filled with fireside discussions, wildlife watching and stunningly beautiful walks. With the nearest mobile signal a ten minute walk away, it‚Äôs a great place to ditch the digital and truly escape. Head over the bridge to your own private deck that happily houses a clever outdoor-kitchen and shower (complete with hot water). It‚Äôs the perfect spot to fry up breakfast whilst basking in peace and tranquility. There is also a flushing toilet situated just up the hill.And don‚Äôt worry, you‚Äôre not totally left to your own devices, on arrival you can expect bed linen, towels and a load of dry wood and kindling. If you feel the need to leave your new found homestead in the trees then the local area has lots of suitably chilled things to do. Head out on a moorland walk to take in some magical views - and perhaps even grab a pint at the local pub en route. Further afield, the stunning Elan Valley, a landscape bursting with impressive dams and reservoirs, is well worthy of an explore. And for those needing supplies - and perhaps a flat white - then the friendly market town of Builth Wells is just down the road.\', \'\', \'\', \'\', \'Other things to note\\nYou are entering a remote woodland hideaway for a digital detox: there is very patchy mobile signal and limited internet connectivity.\']'

In [ ]:
def combine_description_strings(df):
    df = df.dropna(subset=['Description'])
    df["Description"] = df["Description"].apply(lambda x: x.replace("'About this space', ", '').replace("'', ", '').replace('[', '').replace(']', '').replace('\\n', '.      ').replace("''", '').split(" "))
    df["Description"] = df["Description"].apply(lambda x: " ".join(x))
    return df

In [ ]:
df[['guests','beds','bedrooms','bathrooms',]]

    guests  beds bedrooms  bathrooms
0        2   1.0      NaN        1.0
1        3   3.0        1        0.0
2        4   2.0        1        1.5
3        2   NaN      NaN        1.0
5        4   3.0        2        1.0
..     ...   ...      ...        ...
982      4   2.0        2        1.5
983      2   1.0        1        1.0
984      4   2.0        2        1.5
985      6   3.0        2        2.0
987      4   2.0        2        1.0

[890 rows x 4 columns]

In [ ]:
df[['guests','beds','bedrooms','bathrooms']].fillna(1).isnull().sum()

guests       0
beds         0
bedrooms     0
bathrooms    0
dtype: int64

In [ ]:
print(df['beds'].to_list())

[1.0, 3.0, 2.0, nan, 3.0, 2.0, 5.0, 3.0, 2.0, 4.0, 1.0, 4.0, 3.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 1.0, 1.0, 2.0, 1.0, 2.0, 4.0, 2.0, 4.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 4.0, 1.0, 2.0, 2.0, 1.0, 3.0, 3.0, 2.0, 1.0, 1.0, 6.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 4.0, 1.0, 1.0, 3.0, nan, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 2.0, 5.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, nan, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 3.0, 1.0, 9.0, 2.0, 4.0, 1.0, 2.0, 1.0, 1.0, 4.0, 5.0, 1.0, 2.0, 1.0, 3.0, 2.0, 3.0, 3.0, 3.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 2.0, 3.0, 2.0, 5.0, 6.0, 1.0, 1.0, 1.0, 4.0, 2.0, 1.0, 2.0, 1.0, 4.0, 4.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 1.0, 3.0, 1.0, 3.0, 3.0, 6.0, 1.0, 1.0, 1.0, 1.0, 9.0, 1.0, 2.0, 3.0, 2.0, 2.0, 4.0, 5.0, nan, 3.0, 1.0, nan, 2.0, 1.0, nan, 1.0, 1.0, 2.0, 1.0, nan, 1.0, 4.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 2.0, 1.0, 3.0, 3.0, 4.0, 3.0, 1.0, 2.0, 2.0, 1.0, 7.0, nan, nan, 1.0, 2.0, 4.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 5.0, 1.0, 1.0, nan, 1.0, 2.0, 3.0, 1.0, 3.0, 5.0, 1.0, 1.0, nan, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, nan, 1.0, 1.0, 3.0, 1.0, 1.0, 5.0, 1.0, 5.0, 2.0, 1.0, 2.0, 2.0, 3.0, 2.0, 3.0, 4.0, 1.0, 1.0, 2.0, 2.0, 5.0, 1.0, 5.0, 2.0, 2.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 1.0, 2.0, 3.0, 3.0, 1.0, 3.0, 1.0, 1.0, 2.0, 1.0, nan, 1.0, 5.0, 1.0, 3.0, 3.0, 1.0, nan, 3.0, 4.0, 7.0, nan, 1.0, 1.0, 1.0, 2.0, 1.0, 3.0, 2.0, 1.0, nan, 1.0, nan, 1.0, 1.0, 3.0, 7.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 2.0, 1.0, 2.0, 1.0, 3.0, 2.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 3.0, 2.0, 1.0, 6.0, nan, 3.0, 5.0, 1.0, 1.0, 4.0, 3.0, 1.0, 2.0, 1.0, 1.0, 1.0, 3.0, 2.0, 1.0, 1.0, 6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 3.0, 3.0, 1.0, 1.0, 1.0, 2.0, 1.0, nan, 1.0, 2.0, 2.0, 2.0, 1.0, 3.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 3.0, 5.0, 3.0, 4.0, 2.0, 3.0, 6.0, 3.0, 1.0, 1.0, 1.0, 4.0, 1.0, 1.0, 3.0, 3.0, 5.0, 7.0, 3.0, 5.0, 2.0, 1.0, 1.0, 2.0, 3.0, 1.0, 1.0, 5.0, 1.0, 4.0, 8.0, 1.0, 4.0, 5.0, 1.0, 3.0, 1.0, 3.0, 5.0, 1.0, 2.0, 5.0, 6.0, 6.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.0, 2.0, 4.0, 1.0, 1.0, 2.0, 2.0, 1.0, 3.0, 4.0, 8.0, 2.0, 2.0, 5.0, 1.0, nan, 3.0, 4.0, 4.0, 3.0, nan, 1.0, 3.0, 2.0, 1.0, 3.0, 3.0, 1.0, 1.0, 3.0, 2.0, 4.0, 7.0, 3.0, 3.0, 4.0, 1.0, 5.0, 2.0, 2.0, 1.0, 2.0, 4.0, 1.0, 5.0, 1.0, 2.0, 1.0, 1.0, 3.0, nan, 4.0, 1.0, 3.0, 1.0, nan, 2.0, 6.0, 2.0, 2.0, 3.0, 4.0, 2.0, 2.0, 3.0, 6.0, 4.0, 8.0, 5.0, 3.0, 2.0, 7.0, 2.0, 4.0, 1.0, 1.0, 3.0, 1.0, 10.0, 5.0, 6.0, 5.0, 4.0, 3.0, 3.0, 1.0, 1.0, 3.0, 3.0, 1.0, 5.0, 3.0, 5.0, 3.0, 3.0, 5.0, 3.0, 1.0, 3.0, 2.0, 2.0, 2.0, 5.0, 1.0, 4.0, 3.0, nan, 3.0, 5.0, 3.0, 1.0, 1.0, 5.0, 7.0, 3.0, 3.0, 5.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, 1.0, 1.0, 2.0, 2.0, 5.0, 1.0, 1.0, 1.0, 1.0, 4.0, 1.0, 4.0, 4.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 5.0, 1.0, 4.0, 1.0, 1.0, 4.0, 4.0, 2.0, 1.0, 3.0, 1.0, 5.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 3.0, 2.0, 1.0, 1.0, 1.0, nan, 1.0, 4.0, 7.0, 1.0, 1.0, 1.0, 3.0, 1.0, 17.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 4.0, 3.0, 1.0, 1.0, 2.0, nan, 2.0, 4.0, 2.0, 1.0, 1.0, 1.0, 4.0, 6.0, 3.0, 2.0, 1.0, 2.0, 2.0, 1.0, 5.0, 4.0, 2.0, 1.0, 1.0, 3.0, 3.0, nan, 4.0, 4.0, 1.0, 3.0, 5.0, 3.0, 2.0, 5.0, 4.0, 1.0, 1.0, 6.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 7.0, 1.0, 2.0, 2.0, 4.0, 2.0, 1.0, 3.0, 1.0, 3.0, 1.0, 3.0, 1.0, 1.0, 4.0, 2.0, 2.0, 3.0, 1.0, 2.0, 1.0, 1.0, 6.0, 6.0, 3.0, 2.0, 3.0, 1.0, 1.0, 3.0, 1.0, 1.0, 15.0, 2.0, 2.0, 4.0, 1.0, 1.0, 2.0, 2.0, 2.0, 5.0, 12.0, 1.0, 2.0, 1.0, 5.0, 9.0, 1.0, 1.0, 4.0, 2.0, 2.0, 3.0, 1.0, 1.0, 2.0, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0, 10.0, 3.0, nan, 4.0, 1.0, 3.0, 2.0, 6.0, 3.0, 5.0, 7.0, 1.0, 3.0, 3.0, 2.0, 2.0, 7.0, 4.0, 4.0, 1.0, 1.0, 2.0, 1.0, 2.0, 3.0, 1.0, 2.0, 7.0, 2.0, 4.0, 2.0, 5.0, 5.0, 5.0, 2.0, 3.0, 7.0, 2.0, 4.0, 5.0, 2.0, 2.0, 4.0, 5.0, 1.0, 2.0, 4.0, 1.0, 5.0, 2.0, 3.0, 7.0, 2.0, 6.0, 1.0, 4.0, 1.0, 3.0, 5.0, 1.0, 1.0, 3.0, 1.0, 2.0, 4.0, 3.0, 1.0, 7.0, 2.0, 4.0, 1.0, 1.0, 2.0, 3.0, 5.0, nan, 3.0, nan, 4.0, 1.0, 2.0, 1.0, 2.0, 3.0, 5.0, 5.0, 8.0, 5.0, 3.0, 2.0, 3.0, 8.0, 1.0, 1.0, 3.0, 3.0, 4.0, 4.0, 3.0, 3.0, 6.0, 6.0, 2.0, 1.0, 3.0, 1.0, 5.0, 2.0, 1.0, 2.0, nan, 1.0, 2.0, 3.0, 10.0, 5.0, 1.0, 2.0, 6.0, 2.0, 2.0, 2.0, 12.0, 4.0, 1.0, 2.0, 3.0, 1.0, nan, 3.0, 2.0, 1.0, 2.0, 3.0, 2.0]

In [ ]:
print(df['bathrooms'].tolist())

[1.0, 0.0, 1.5, 1.0, 1.0, nan, 1.0, nan, 1.0, 1.0, nan, 1.0, 1.0, nan, 1.0, 1.0, 1.5, nan, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 2.5, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, nan, 1.5, nan, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 2.0, 1.5, 1.0, 4.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.5, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 2.0, nan, 1.0, nan, 1.0, 5.5, nan, 1.0, nan, 1.0, 1.0, 1.0, 2.0, nan, 1.0, nan, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 2.0, 0.0, 1.0, 0.0, 1.0, 1.0, nan, nan, nan, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, nan, 2.0, 1.5, 1.0, 1.5, 1.0, 1.0, 2.0, 1.0, 1.0, 1.5, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, nan, 2.0, 1.5, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.5, 3.0, 1.0, 1.5, nan, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, nan, 1.5, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 2.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, nan, 1.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, nan, 1.0, 2.0, 1.0, 1.0, 2.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, nan, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.5, 2.0, 2.0, 1.0, 1.0, 2.5, 2.0, 1.0, 1.0, 1.0, 3.5, 1.0, 1.0, 3.0, 1.0, 1.0, 1.5, 1.0, 3.0, 1.5, 1.0, 1.0, 2.0, 2.5, 1.0, nan, 3.5, 1.0, 1.0, 4.0, 1.0, 1.5, 3.5, 1.0, 1.5, 1.0, 2.0, 2.5, 1.0, 1.5, 4.5, 3.5, 4.0, 1.0, 1.0, 1.0, 1.0, nan, 2.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.5, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.5, 1.0, 2.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 1.5, 2.0, 3.0, 1.0, 2.5, 1.5, 1.0, 2.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.5, 1.0, 2.0, nan, 1.0, nan, 1.5, nan, 1.0, 2.0, 5.5, 2.0, 1.5, 1.0, 2.0, 1.0, 1.0, 2.0, 3.5, 2.0, 3.0, 3.5, 1.0, 2.0, 2.5, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.0, 2.0, 4.0, 1.5, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 2.0, 1.0, 2.0, 2.0, 1.5, 2.0, 2.0, 1.0, 1.0, 2.0, 1.5, 1.0, 2.0, 1.5, 3.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 5.0, 1.0, 2.0, 1.5, 1.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.5, nan, 1.0, 0.0, 2.0, 1.0, 1.5, 1.5, 1.0, nan, 1.0, 2.0, 1.5, nan, 1.0, nan, 0.0, 1.0, 1.0, 1.0, 3.0, 1.0, 3.0, nan, nan, 1.0, 3.0, 1.0, 1.0, 1.5, 1.0, 1.0, 1.0, 1.5, 1.5, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, nan, 2.0, 1.5, 10.0, 1.0, 1.5, 1.5, 1.5, 1.0, 1.0, nan, 1.0, 1.0, 1.0, 1.0, nan, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 5.0, 1.5, 1.0, 1.0, 1.0, nan, nan, 3.0, 2.0, 1.0, nan, nan, 2.0, 4.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.5, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 3.0, 2.0, 1.5, 3.5, 3.0, 1.0, 1.0, 4.5, 1.0, 1.0, 1.0, nan, nan, 1.0, 4.5, 1.0, 1.0, 1.0, 2.0, 1.0, nan, 2.0, 4.0, 2.0, 1.0, 2.0, nan, 1.0, 3.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, nan, 4.0, 3.0, 3.0, 1.0, 1.0, 1.5, nan, 2.0, 2.0, 1.0, 4.0, 1.0, 2.0, 2.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 2.5, 1.0, 0.0, 0.0, 3.5, 5.0, nan, 1.0, 2.0, 1.5, 1.0, 1.0, nan, 1.0, nan, 1.0, 2.5, 2.0, 2.0, 1.0, 1.5, 1.0, 2.5, 0.0, 1.5, 1.0, 1.0, 1.0, 2.5, 1.0, 3.5, 3.0, 1.0, 1.5, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.5, 1.5, 2.5, 5.5, 2.0, 2.0, 1.5, 1.0, 1.0, 2.0, 3.5, 1.0, 1.0, 2.0, 1.0, 2.0, 2.0, 1.0, 1.0, 1.0, 2.0, nan, 1.0, 1.0, 1.0, 2.0, 1.0, nan, 2.0, 1.0, 1.0, 1.0, 1.0, nan, 4.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.5, nan, 1.0, nan, 1.5, 1.0, 1.0, 1.0, 1.0, 1.0, 2.5, 3.0, 2.5, 2.0, 1.0, 1.0, 1.0, 4.5, 1.0, 1.0, 1.5, 2.0, 2.5, 4.0, 2.0, 1.0, 4.0, 2.5, 1.0, 1.0, 2.0, 1.0, 3.5, 1.0, 1.0, 2.0, nan, 1.0, 1.5, 1.0, 2.5, 2.5, nan, 1.0, 2.0, 1.0, 1.0, 2.0, 5.5, 3.0, 1.0, 1.0, 2.0, 1.0, nan, 2.0, 1.5, 1.0, 1.5, 2.0, 1.0]

In [ ]:
 print(df['guests'].tolist())

['2', '3', '4', '2', '4', '3', '6', '4', '3', '5', '2', '5', '5', '2', '4', '4', '2', '5', '8', '2', '2', '2', '4', '4', '5', '3', '4', '2', '4', '4', '2', '2', '2', '7', '4', '2', '2', '6', '2', '2', '8', '2', '4', '6', '4', '6', '4', '4', '2', '2', '6', '2', '2', '2', '2', '2', '2', '2', '2', '6', '2', '2', '4', '2', '2', '4', '2', '2', '2', '3', '2', '6', '4', '7', '2', '2', '3', '2', '4', '4', '4', '2', '4', '4', '2', '4', '4', '3', '4', '4', '4', '2', '4', '4', '5', '2', '2', '2', '4', '2', '4', '2', '4', '2', '2', '4', '2', '8', '3', '5', '4', '3', '4', '5', '2', '2', '2', '6', '2', '14', '4', '4', '2', '4', '2', '2', '4', '8', '2', '4', '2', '4', '4', '4', '4', '4', '2', '4', '2', '3', '4', '2', '4', '4', '3', '2', '5', '11', '2', '2', '2', '6', '3', '2', '4', '2', '7', '5', '2', '4', '4', '2', '4', '2', '6', '6', '2', '3', '4', '8', '2', '2', '2', '2', '16', '2', '4', '4', '4', '4', '6', '7', nan, '3', '2', nan, '4', '2', '4', '2', '2', '2', '2', '2', '2', '6', '2', '2', '3', '5', '4', '4', '2', '2', '5', '2', '4', '3', '5', '4', '2', '2', '4', '2', '6', nan, '4', '2', '4', '4', '2', '2', '4', '2', '2', '2', '4', '2', '6', '2', '2', '2', '2', '2', '2', '2', '2', nan, '6', '2', '2', nan, '2', '4', '5', '2', '4', '8', '2', '2', nan, '2', '2', '2', '2', '2', '2', '2', '4', '2', '2', '2', '2', '2', '2', nan, '3', '2', '4', '2', '2', '6', '2', '8', '4', '2', '5', '4', '4', '2', '5', '8', '2', '2', '2', '4', '4', '2', '8', '4', '4', '4', '2', '2', '2', '2', '6', '4', '4', '5', '6', '2', '4', '2', '2', '4', '2', nan, '2', '7', '2', '6', '4', '2', nan, '4', '5', '10', nan, '2', '4', '2', '4', '2', '4', '4', '2', '2', '2', nan, '2', '2', '4', '6', '2', '2', '4', '2', '2', '4', '3', '2', '4', '2', '4', '4', '2', '2', '2', '2', '4', '2', '4', '4', '2', '7', nan, '4', '6', '2', '2', '4', '4', '2', '3', '2', '2', '2', '6', '2', '2', '2', '8', '2', '2', '2', '2', '2', '2', '4', '2', '2', '4', '7', '2', '2', '2', '3', '2', '2', '2', '4', '4', '5', '2', '5', '2', '2', '2', '4', '2', '4', '4', '6', '6', '4', '6', '2', '4', '12', '4', '2', '4', '2', '8', '2', '2', '6', '6', '5', '12', '4', '10', '4', '2', '2', '4', '4', '4', '2', '8', '2', '6', '14', '2', '5', '10', '2', '5', '2', '4', '6', '2', '2', '8', '6', '9', '2', '2', '4', '2', '2', '5', '4', '3', '2', '2', '3', '4', '2', '4', '6', '8', '6', '4', '5', '2', '2', '4', '4', '6', '4', '6', '2', '4', '2', '2', '4', '4', '2', '2', '4', '3', '4', '8', '4', '6', '5', '2', '8', '4', '3', '2', '4', '4', '2', '6', '2', '4', '2', '2', '4', nan, '5', '2', '5', '2', '2', '4', '8', '4', '4', '4', '8', '3', '4', '4', '8', '6', '12', '7', '4', '4', '10', '4', '6', '2', '2', '4', '2', '12', '6', 'Somerford Keynes England United Kingdom', '6', '4', '4', '4', '2', '2', '4', '4', '2', '6', '4', '6', '6', '6', '6', '4', '2', '4', '4', '2', '2', '8', '2', '8', '4', nan, '4', '5', '4', '2', '4', '6', '10', '4', '5', '8', '4', '4', '5', '4', '4', '4', '2', '2', '3', '4', '6', '2', '2', '3', '2', '5', '2', '4', '5', '2', '2', '2', '2', '1', '2', '2', '10', '2', '6', '6', '2', '5', '8', '4', '4', '4', '2', '6', '2', '3', '4', '2', '2', '2', '6', '3', '2', '2', '2', '2', '2', '4', '6', '4', '2', '2', '8', '2', '16', '2', '2', '2', '2', '4', '4', '2', '2', '2', '2', '3', '2', '2', '4', '2', '2', '3', '2', '16', '6', '2', '2', '4', nan, '3', '16', '4', '2', '2', '2', '6', '8', '4', '5', '2', '3', '4', '2', '11', '6', '3', '2', '2', '6', '5', '2', '6', '5', '2', '4', '6', '6', '4', '9', '8', '2', '3', '6', '2', '2', '2', '2', '4', '2', '10', '2', '4', '3', '4', '2', '2', '6', '2', '6', '2', '4', '2', '2', '8', '4', '4', '5', '2', '4', '4', '2', '9', '10', '6', '4', '4', '2', '2', '5', '2', '2', '16', '4', '4', '8', '2', '2', '4', '4', '4', '6', '12', '4', '2', '4', '7', '10', '2', '2', '4', '2', '2', '5', '2', '3', '3', '4', '4', '4', '6', '2', '6', '6', '6', '2', '5', '2', '4', '4', '8', '4', '9', '8', '4', '6', '6', '4', '2', '10', '5', '6', '2', '2', '4', '2', '4', '4', '2', '4', '8', '4', '6', '2', '6', '9', '6', '2', '4', '12', '5', '6', '8', '4', '4', '5', '6', '4', '4', '6', '3', '6', '3', '4', '8', '4', '6', '2', '4', '2', '4', '8', '2', '2', '4', '2', '4', '4', '5', '2', '10', '4', '5', '2', '2', '4', '4', '8', '2', '4', nan, '6', '2', '4', '2', '4', '4', '10', '8', '10', '8', '5', '4', '4', '9', '2', '4', '2', '4', '6', '6', '4', '4', '8', '8', '6', '2', '8', '2', '6', '4', '2', '4', nan, '2', '3', '4', '10', '9', '2', '4', '8', '4', '4', '6', '16', '8', '2', '4', '4', '2', nan, '4', '4', '2', '4', '6', '4']

In [ ]:
print(df['bedrooms'].to_list())

[nan, '1', '1', nan, '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', nan, '2', '1', '1', '1', '1', '1', '1', '1', nan, nan, '1', '1', '1', '1', '1', nan, '1', '1', '1', '2', '1', nan, '2', '1', nan, '1', '1', '2', '1', '1', '1', '1', '2', '1', '1', '1', '1', '1', '1', nan, '1', '2', '1', nan, '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', '1', '1', '1', nan, '2', '1', '1', '2', '1', nan, '2', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', nan, '1', '1', '1', nan, '2', '1', '1', '1', '1', '2', '1', '1', '1', '2', '1', '5', '1', '1', nan, '1', '1', '1', '1', '3', '1', '2', '1', '1', '1', '1', '2', '2', '1', '1', '1', '1', '1', '1', '2', nan, '1', '1', '2', '3', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', nan, nan, '1', nan, '1', '1', nan, '1', '4', '1', '1', '1', '1', '8', '1', '2', '1', '2', '2', '2', '3', nan, '2', nan, nan, '1', '1', '1', '1', nan, '1', nan, '1', nan, '2', nan, '1', '1', '1', nan, '1', '1', '1', '3', '1', '1', '1', '3', '2', nan, '1', '2', nan, '2', nan, '2', '1', '1', '2', '1', '1', '2', nan, '1', '1', '1', '1', '2', '1', '1', '1', '1', '1', '1', '1', '1', nan, '3', '1', '1', nan, '1', '1', '2', nan, '2', '4', '1', '1', nan, '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', '2', '1', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', '1', '3', '1', nan, '1', '1', '2', '1', '3', '1', '2', '1', '1', '1', '1', '1', '2', '1', '1', '2', '2', '1', '2', '1', '1', '1', '1', nan, '1', '3', '1', '3', '2', '1', nan, '1', '2', '3', nan, '1', '1', nan, '1', '1', '2', '1', nan, '1', '1', nan, '1', '1', '2', '2', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', '2', '1', '1', '1', '1', '1', '1', '1', '2', '1', '1', '4', nan, '2', '3', '1', '1', '2', '2', nan, '1', '1', '1', '1', '3', '1', nan, '1', '3', '1', '1', '1', '1', '1', '1', '2', '1', '1', '2', '4', nan, nan, '1', '1', '1', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', '1', '1', '2', '2', '1', '2', '3', '1', '2', '3', '2', '1', '1', '1', '3', nan, '1', '3', '2', '2', '3', '2', '4', '1', '1', '1', '2', '2', '1', '1', '4', '1', '2', '6', '1', '2', '4', '1', '3', '1', '2', '2', nan, '1', '5', '3', '6', '1', '1', '1', '1', '1', '2', '1', '1', '1', '1', '2', nan, '1', '2', '3', '4', '2', '1', '3', '1', '1', '1', '2', '3', '2', '3', '1', '2', '1', '1', '2', '2', '1', '1', '2', '2', '2', '4', '2', '2', '2', nan, '4', '1', '1', '1', '1', '2', '1', '3', '1', '1', '1', '1', '2', nan, '2', '1', '2', '1', '1', '1', '5', '2', '1', '1', '2', nan, '1', '2', '5', '2', '6', '3', '2', '2', '5', '2', '2', '1', '1', '2', '1', '5', '3', 'https://www.airbnb.co.uk/rooms/49009981?adults=1&category_tag=Tag%3A677&children=0&infants=0&search_mode=flex_destinations_search&check_in=2022-04-18&check_out=2022-04-25&previous_page_section_name=1000&federated_search_id=0b044c1c-8d17-4b03-bffb-5de13ff710bc', '3', '2', '2', '2', '1', '1', '2', '2', '1', '3', '2', '3', '3', '3', '3', '2', '1', '2', '2', '1', '1', '3', '1', '4', '2', nan, '2', '2', '2', '1', '1', '3', '5', '2', '2', '3', '2', '2', '1', '2', '2', '2', '1', '1', '1', '1', '3', '1', '1', '1', '1', '2', '1', '2', '3', '1', '1', '1', '1', '1', '1', '1', '4', '1', '3', '1', '1', '2', '3', '1', '1', '2', '1', '1', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', nan, '1', '1', '3', '1', '1', '1', '2', '1', '10', '1', '1', '1', '1', '1', '2', '1', '1', '1', '1', '2', '1', '1', '2', '1', '1', '1', '1', '4', '2', '1', nan, '1', nan, '1', '3', '2', '1', '1', nan, '3', '3', '2', '2', '1', '1', '1', nan, '3', '2', '1', '1', nan, '2', '3', '1', '3', '2', '1', '2', '4', '2', '2', '4', '3', '1', '2', '3', nan, '1', '1', '1', '1', '1', '5', '1', '1', '1', '3', '1', '1', '3', '1', '3', nan, '2', '1', '1', '3', nan, '1', '1', '1', '1', '1', '1', '5', '5', '2', '2', '1', '1', '1', '3', '1', '1', '7', '2', '2', '3', '1', '1', '1', '1', '2', '3', '5', '1', nan, '1', '3', '5', '1', nan, '2', '1', '1', '2', '1', '1', '1', nan, '2', '2', '2', '1', '3', '3', '2', '1', '2', '1', '2', '2', '4', '1', '4', '4', '1', '2', '2', '2', '1', '4', '2', '3', '1', '1', '2', '1', '2', '1', '1', '2', '4', '2', '3', '1', '3', '3', '3', '1', '2', '6', '2', '3', '3', '1', '2', '3', '3', '1', '2', '3', '1', '3', '1', '3', '3', '1', '3', '1', '1', '1', '2', '4', '1', '1', '2', '1', '2', '3', '2', '1', '4', '1', '3', '1', '1', '1', '2', '4', '1', '1', nan, '2', '1', '2', '1', '2', '2', '5', '4', '5', '4', '2', '2', '2', '5', '1', '1', '2', '2', '4', '4', '3', '2', '4', '4', '2', '1', '3', '1', '4', '2', '1', '2', nan, '1', '2', '2', '5', '4', '1', '1', '4', '1', '2', '2', '6', '4', '1', '2', '2', '1', nan, '2', '2', '1', '2', '2', '2']

In [ ]:
df.loc[df["guests"] == 'Somerford Keynes England United Kingdom', "guests"] = '1'
print(df['guests'].tolist())

['2', '3', '4', '2', '4', '3', '6', '4', '3', '5', '2', '5', '5', '2', '4', '4', '2', '5', '8', '2', '2', '2', '4', '4', '5', '3', '4', '2', '4', '4', '2', '2', '2', '7', '4', '2', '2', '6', '2', '2', '8', '2', '4', '6', '4', '6', '4', '4', '2', '2', '6', '2', '2', '2', '2', '2', '2', '2', '2', '6', '2', '2', '4', '2', '2', '4', '2', '2', '2', '3', '2', '6', '4', '7', '2', '2', '3', '2', '4', '4', '4', '2', '4', '4', '2', '4', '4', '3', '4', '4', '4', '2', '4', '4', '5', '2', '2', '2', '4', '2', '4', '2', '4', '2', '2', '4', '2', '8', '3', '5', '4', '3', '4', '5', '2', '2', '2', '6', '2', '14', '4', '4', '2', '4', '2', '2', '4', '8', '2', '4', '2', '4', '4', '4', '4', '4', '2', '4', '2', '3', '4', '2', '4', '4', '3', '2', '5', '11', '2', '2', '2', '6', '3', '2', '4', '2', '7', '5', '2', '4', '4', '2', '4', '2', '6', '6', '2', '3', '4', '8', '2', '2', '2', '2', '16', '2', '4', '4', '4', '4', '6', '7', nan, '3', '2', nan, '4', '2', '4', '2', '2', '2', '2', '2', '2', '6', '2', '2', '3', '5', '4', '4', '2', '2', '5', '2', '4', '3', '5', '4', '2', '2', '4', '2', '6', nan, '4', '2', '4', '4', '2', '2', '4', '2', '2', '2', '4', '2', '6', '2', '2', '2', '2', '2', '2', '2', '2', nan, '6', '2', '2', nan, '2', '4', '5', '2', '4', '8', '2', '2', nan, '2', '2', '2', '2', '2', '2', '2', '4', '2', '2', '2', '2', '2', '2', nan, '3', '2', '4', '2', '2', '6', '2', '8', '4', '2', '5', '4', '4', '2', '5', '8', '2', '2', '2', '4', '4', '2', '8', '4', '4', '4', '2', '2', '2', '2', '6', '4', '4', '5', '6', '2', '4', '2', '2', '4', '2', nan, '2', '7', '2', '6', '4', '2', nan, '4', '5', '10', nan, '2', '4', '2', '4', '2', '4', '4', '2', '2', '2', nan, '2', '2', '4', '6', '2', '2', '4', '2', '2', '4', '3', '2', '4', '2', '4', '4', '2', '2', '2', '2', '4', '2', '4', '4', '2', '7', nan, '4', '6', '2', '2', '4', '4', '2', '3', '2', '2', '2', '6', '2', '2', '2', '8', '2', '2', '2', '2', '2', '2', '4', '2', '2', '4', '7', '2', '2', '2', '3', '2', '2', '2', '4', '4', '5', '2', '5', '2', '2', '2', '4', '2', '4', '4', '6', '6', '4', '6', '2', '4', '12', '4', '2', '4', '2', '8', '2', '2', '6', '6', '5', '12', '4', '10', '4', '2', '2', '4', '4', '4', '2', '8', '2', '6', '14', '2', '5', '10', '2', '5', '2', '4', '6', '2', '2', '8', '6', '9', '2', '2', '4', '2', '2', '5', '4', '3', '2', '2', '3', '4', '2', '4', '6', '8', '6', '4', '5', '2', '2', '4', '4', '6', '4', '6', '2', '4', '2', '2', '4', '4', '2', '2', '4', '3', '4', '8', '4', '6', '5', '2', '8', '4', '3', '2', '4', '4', '2', '6', '2', '4', '2', '2', '4', nan, '5', '2', '5', '2', '2', '4', '8', '4', '4', '4', '8', '3', '4', '4', '8', '6', '12', '7', '4', '4', '10', '4', '6', '2', '2', '4', '2', '12', '6', '1', '6', '4', '4', '4', '2', '2', '4', '4', '2', '6', '4', '6', '6', '6', '6', '4', '2', '4', '4', '2', '2', '8', '2', '8', '4', nan, '4', '5', '4', '2', '4', '6', '10', '4', '5', '8', '4', '4', '5', '4', '4', '4', '2', '2', '3', '4', '6', '2', '2', '3', '2', '5', '2', '4', '5', '2', '2', '2', '2', '1', '2', '2', '10', '2', '6', '6', '2', '5', '8', '4', '4', '4', '2', '6', '2', '3', '4', '2', '2', '2', '6', '3', '2', '2', '2', '2', '2', '4', '6', '4', '2', '2', '8', '2', '16', '2', '2', '2', '2', '4', '4', '2', '2', '2', '2', '3', '2', '2', '4', '2', '2', '3', '2', '16', '6', '2', '2', '4', nan, '3', '16', '4', '2', '2', '2', '6', '8', '4', '5', '2', '3', '4', '2', '11', '6', '3', '2', '2', '6', '5', '2', '6', '5', '2', '4', '6', '6', '4', '9', '8', '2', '3', '6', '2', '2', '2', '2', '4', '2', '10', '2', '4', '3', '4', '2', '2', '6', '2', '6', '2', '4', '2', '2', '8', '4', '4', '5', '2', '4', '4', '2', '9', '10', '6', '4', '4', '2', '2', '5', '2', '2', '16', '4', '4', '8', '2', '2', '4', '4', '4', '6', '12', '4', '2', '4', '7', '10', '2', '2', '4', '2', '2', '5', '2', '3', '3', '4', '4', '4', '6', '2', '6', '6', '6', '2', '5', '2', '4', '4', '8', '4', '9', '8', '4', '6', '6', '4', '2', '10', '5', '6', '2', '2', '4', '2', '4', '4', '2', '4', '8', '4', '6', '2', '6', '9', '6', '2', '4', '12', '5', '6', '8', '4', '4', '5', '6', '4', '4', '6', '3', '6', '3', '4', '8', '4', '6', '2', '4', '2', '4', '8', '2', '2', '4', '2', '4', '4', '5', '2', '10', '4', '5', '2', '2', '4', '4', '8', '2', '4', nan, '6', '2', '4', '2', '4', '4', '10', '8', '10', '8', '5', '4', '4', '9', '2', '4', '2', '4', '6', '6', '4', '4', '8', '8', '6', '2', '8', '2', '6', '4', '2', '4', nan, '2', '3', '4', '10', '9', '2', '4', '8', '4', '4', '6', '16', '8', '2', '4', '4', '2', nan, '4', '4', '2', '4', '6', '4']

In [ ]:
df.loc[df['bedrooms']=='https://www.airbnb.co.uk/rooms/49009981?adults=1&category_tag=Tag%3A677&children=0&infants=0&search_mode=flex_destinations_search&check_in=2022-04-18&check_out=2022-04-25&previous_page_section_name=1000&federated_search_id=0b044c1c-8d17-4b03-bffb-5de13ff710bc','bedrooms']='1'

In [ ]:
print(df['bedrooms'].tolist())

[nan, '1', '1', nan, '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', nan, '2', '1', '1', '1', '1', '1', '1', '1', nan, nan, '1', '1', '1', '1', '1', nan, '1', '1', '1', '2', '1', nan, '2', '1', nan, '1', '1', '2', '1', '1', '1', '1', '2', '1', '1', '1', '1', '1', '1', nan, '1', '2', '1', nan, '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', '1', '1', '1', nan, '2', '1', '1', '2', '1', nan, '2', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', nan, '1', '1', '1', nan, '2', '1', '1', '1', '1', '2', '1', '1', '1', '2', '1', '5', '1', '1', nan, '1', '1', '1', '1', '3', '1', '2', '1', '1', '1', '1', '2', '2', '1', '1', '1', '1', '1', '1', '2', nan, '1', '1', '2', '3', '1', '1', '1', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', nan, nan, '1', nan, '1', '1', nan, '1', '4', '1', '1', '1', '1', '8', '1', '2', '1', '2', '2', '2', '3', nan, '2', nan, nan, '1', '1', '1', '1', nan, '1', nan, '1', nan, '2', nan, '1', '1', '1', nan, '1', '1', '1', '3', '1', '1', '1', '3', '2', nan, '1', '2', nan, '2', nan, '2', '1', '1', '2', '1', '1', '2', nan, '1', '1', '1', '1', '2', '1', '1', '1', '1', '1', '1', '1', '1', nan, '3', '1', '1', nan, '1', '1', '2', nan, '2', '4', '1', '1', nan, '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', nan, '1', '1', '2', '1', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', '1', '3', '1', nan, '1', '1', '2', '1', '3', '1', '2', '1', '1', '1', '1', '1', '2', '1', '1', '2', '2', '1', '2', '1', '1', '1', '1', nan, '1', '3', '1', '3', '2', '1', nan, '1', '2', '3', nan, '1', '1', nan, '1', '1', '2', '1', nan, '1', '1', nan, '1', '1', '2', '2', '1', '1', '1', '1', '1', '1', '2', '1', nan, '1', '2', '1', '1', '1', '1', '1', '1', '1', '2', '1', '1', '4', nan, '2', '3', '1', '1', '2', '2', nan, '1', '1', '1', '1', '3', '1', nan, '1', '3', '1', '1', '1', '1', '1', '1', '2', '1', '1', '2', '4', nan, nan, '1', '1', '1', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', '1', '1', '2', '2', '1', '2', '3', '1', '2', '3', '2', '1', '1', '1', '3', nan, '1', '3', '2', '2', '3', '2', '4', '1', '1', '1', '2', '2', '1', '1', '4', '1', '2', '6', '1', '2', '4', '1', '3', '1', '2', '2', nan, '1', '5', '3', '6', '1', '1', '1', '1', '1', '2', '1', '1', '1', '1', '2', nan, '1', '2', '3', '4', '2', '1', '3', '1', '1', '1', '2', '3', '2', '3', '1', '2', '1', '1', '2', '2', '1', '1', '2', '2', '2', '4', '2', '2', '2', nan, '4', '1', '1', '1', '1', '2', '1', '3', '1', '1', '1', '1', '2', nan, '2', '1', '2', '1', '1', '1', '5', '2', '1', '1', '2', nan, '1', '2', '5', '2', '6', '3', '2', '2', '5', '2', '2', '1', '1', '2', '1', '5', '3', '1', '3', '2', '2', '2', '1', '1', '2', '2', '1', '3', '2', '3', '3', '3', '3', '2', '1', '2', '2', '1', '1', '3', '1', '4', '2', nan, '2', '2', '2', '1', '1', '3', '5', '2', '2', '3', '2', '2', '1', '2', '2', '2', '1', '1', '1', '1', '3', '1', '1', '1', '1', '2', '1', '2', '3', '1', '1', '1', '1', '1', '1', '1', '4', '1', '3', '1', '1', '2', '3', '1', '1', '2', '1', '1', '1', '1', '1', '1', '2', '1', '2', '1', '1', '1', '1', nan, '1', '1', '3', '1', '1', '1', '2', '1', '10', '1', '1', '1', '1', '1', '2', '1', '1', '1', '1', '2', '1', '1', '2', '1', '1', '1', '1', '4', '2', '1', nan, '1', nan, '1', '3', '2', '1', '1', nan, '3', '3', '2', '2', '1', '1', '1', nan, '3', '2', '1', '1', nan, '2', '3', '1', '3', '2', '1', '2', '4', '2', '2', '4', '3', '1', '2', '3', nan, '1', '1', '1', '1', '1', '5', '1', '1', '1', '3', '1', '1', '3', '1', '3', nan, '2', '1', '1', '3', nan, '1', '1', '1', '1', '1', '1', '5', '5', '2', '2', '1', '1', '1', '3', '1', '1', '7', '2', '2', '3', '1', '1', '1', '1', '2', '3', '5', '1', nan, '1', '3', '5', '1', nan, '2', '1', '1', '2', '1', '1', '1', nan, '2', '2', '2', '1', '3', '3', '2', '1', '2', '1', '2', '2', '4', '1', '4', '4', '1', '2', '2', '2', '1', '4', '2', '3', '1', '1', '2', '1', '2', '1', '1', '2', '4', '2', '3', '1', '3', '3', '3', '1', '2', '6', '2', '3', '3', '1', '2', '3', '3', '1', '2', '3', '1', '3', '1', '3', '3', '1', '3', '1', '1', '1', '2', '4', '1', '1', '2', '1', '2', '3', '2', '1', '4', '1', '3', '1', '1', '1', '2', '4', '1', '1', nan, '2', '1', '2', '1', '2', '2', '5', '4', '5', '4', '2', '2', '2', '5', '1', '1', '2', '2', '4', '4', '3', '2', '4', '4', '2', '1', '3', '1', '4', '2', '1', '2', nan, '1', '2', '2', '5', '4', '1', '1', '4', '1', '2', '2', '6', '4', '1', '2', '2', '1', nan, '2', '2', '1', '2', '2', '2']

In [ ]:
def set_default_feature_values(df):
    df.loc[:, ["guests", "bedrooms"]] = df.loc[:, ["guests", "bedrooms"]].fillna('1')
    df.loc[:, ["beds", "bathrooms"]] = df.loc[:, ["beds", "bathrooms"]].fillna(1)
    
    # print(df['guests'].tolist())
    df.loc[df["guests"] == 'Somerford Keynes England United Kingdom', "guests"] = '1'
    df.loc[df["bedrooms"] == 'https://www.airbnb.co.uk/rooms/49009981?adults=1&category_tag=Tag%3A677&children=0&infants=0&search_mode=flex_destinations_search&check_in=2022-04-18&check_out=2022-04-25&previous_page_section_name=1000&federated_search_id=0b044c1c-8d17-4b03-bffb-5de13ff710bc', "bedrooms"] = '1'
    return df

In [ ]:
def clean_tabular_data(df):
    df = remove_rows_with_missing_ratings(df)
    df = combine_description_strings(df)
    df = set_default_feature_values(df)
    return df

In [ ]:
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
5,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"['About this space', 'Charming cabin nestled i...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,cfbc88da-e88c-415a-b397-108d0948c4ba,Beachfront,Lancing Beach Apartment,"['About this space', 'An apartment directly on...","['What this place offers', 'Bathroom', 'Hair d...",Lancing United Kingdom,4,2.0,1.5,240,4.9,5.0,5.0,5.0,4.9,4.8,33.0,https://www.airbnb.co.uk/rooms/12680472?adults...,2,NaN
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [ ]:
df=clean_tabular_data(df)
df.to_csv('clean_tabular_data.csv')

C:\Users\admin\AppData\Local\Temp\ipykernel_2896\4213121332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Description"] = df["Description"].apply(lambda x: x.replace("'About this space', ", '').replace("'', ", '').replace('[', '').replace(']', '').replace('\\n', '.      ').replace("''", '').split(" "))
C:\Users\admin\AppData\Local\Temp\ipykernel_2896\4213121332.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Description"] = df["Description"].apply(lambda x: " ".join(x))

In [ ]:
def load_airbnb(df):
    
    df = df.drop(columns=["Unnamed: 19"])
   

    features = df.drop(columns=['Price_Night', 'ID', 'Category', 'Title', 'Description', 'Amenities', 'Location', 'url'])
   
    labels = df["Price_Night"]

    features_labels  = (features, labels)
    return features_labels

In [ ]:
print(df['Category'].unique())

['Treehouses' 'Chalets' 'Amazing pools' 'Offbeat' 'Beachfront']

In [ ]:
features_labels=load_airbnb(df)
feature,labels=features_labels
print(feature)

    guests  beds  bathrooms  Cleanliness_rating  Accuracy_rating  \
0        2   1.0        1.0                 4.6              4.7
1        3   3.0        0.0                 4.3              4.7
2        4   2.0        1.5                 4.2              4.6
3        2   1.0        1.0                 4.8              4.9
5        4   3.0        1.0                 5.0              4.9
..     ...   ...        ...                 ...              ...
982      4   2.0        1.5                 4.9              5.0
983      2   1.0        1.0                 4.8              5.0
984      4   2.0        1.5                 4.8              5.0
985      6   3.0        2.0                 4.7              4.8
987      4   2.0        1.0                 4.9              4.9

     Communication_rating  Location_rating  Check-in_rating  Value_rating  \
0                     4.3              5.0              4.3           4.3
1                     4.6              4.9              4.7           4.5
2                     4.8              4.8              4.8           4.7
3                     4.9              4.9              5.0           4.6
5                     5.0              4.7              5.0           4.7
..                    ...              ...              ...           ...
982                   5.0              5.0              4.9           4.8
983                   4.9              4.9              5.0           4.9
984                   5.0              5.0              5.0           4.8
985                   5.0              5.0              5.0           4.7
987                   4.9              4.9              4.9           4.3

     amenities_count bedrooms
0               13.0        1
1                8.0        1
2               51.0        1
3               23.0        1
5               32.0        2
..               ...      ...
982             33.0        2
983             54.0        1
984             38.0        2
985             24.0        2
987             29.0        2

[830 rows x 11 columns]

In [ ]:
print(feature.shape)

(830, 11)

In [ ]:
print(labels)

0      105
1       92
2       52
3      132
5      143
      ...
982    240
983     78
984    113
985     80
987    104
Name: Price_Night, Length: 830, dtype: int64

In [ ]:
print(labels.shape)

(830,)